inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: false

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Bundler/OrderedGems:
  Enabled: false

# Redis backend is quite big
Metrics/ClassLength:
  Max: 310

Metrics/BlockLength:
  Exclude:
    - '**/spec_helper.rb'
    - '**/**_spec.rb'

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them when introducing an interpolation.
# Use single quotes only if their semantics are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes
